#!/usr/bin/zsh

code --install-extension alexisvt.flutter-snippets
code --install-extension Anan.jetbrains-darcula-theme
code --install-extension Angular.ng-template
code --install-extension BendixMa.dart-data-class-generator
code --install-extension betrider.du-dart-class-generator
code --install-extension bradlc.vscode-tailwindcss
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cstrachan.vcard
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dracula-theme.theme-dracula
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension Durzn.brackethighlighter
code --install-extension eamodio.gitlens
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension FelixAngelov.bloc
code --install-extension file-icons.file-icons
code --install-extension formulahendry.dotnet
code --install-extension GitHub.github-vscode-theme
code --install-extension hzgood.dart-data-class-generator
code --install-extension icrawl.discord-vscode
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension jock.svg
code --install-extension luanpotter.dart-import
code --install-extension marnix.tokyo-night-pro
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-dotnettools.csharp
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.theme-oceanicnext
code --install-extension nomi9995.intellij-merge-tool
code --install-extension patbenatar.advanced-new-file
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.LiveServer
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension sburg.vscode-javascript-booster
code --install-extension Streamlux.vscode-appwrite
code --install-extension SushanShakya.bloc-extended
code --install-extension usernamehw.errorlens
code --install-extension vscode-icons-team.vscode-icons
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.material-theme
